using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ET2_2_Tiempo;
//
//    var openWheatherMapProxy = OpenWheatherMapProxy.FromJson(jsonString);

namespace ET2_2_Tiempo
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.Net.Http;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class OpenWheatherMapProxy
    {
        [JsonProperty("coord")]
        public Coord Coord { get; set; }

        [JsonProperty("weather")]
        public Weather[] Weather { get; set; }

        [JsonProperty("base")]
        public string Base { get; set; }

        [JsonProperty("main")]
        public Main Main { get; set; }

        [JsonProperty("visibility")]
        public long Visibility { get; set; }

        [JsonProperty("wind")]
        public Wind Wind { get; set; }

        [JsonProperty("clouds")]
        public Clouds Clouds { get; set; }

        [JsonProperty("dt")]
        public long Dt { get; set; }

        [JsonProperty("sys")]
        public Sys Sys { get; set; }

        [JsonProperty("timezone")]
        public long Timezone { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("cod")]
        public long Cod { get; set; }
    }

    public partial class Clouds
    {
        [JsonProperty("all")]
        public long All { get; set; }
    }

    public partial class Coord
    {
        [JsonProperty("lon")]
        public double Lon { get; set; }

        [JsonProperty("lat")]
        public double Lat { get; set; }
    }

    public partial class Main
    {
        [JsonProperty("temp")]
        public double Temp { get; set; }

        [JsonProperty("feels_like")]
        public double FeelsLike { get; set; }

        [JsonProperty("temp_min")]
        public double TempMin { get; set; }

        [JsonProperty("temp_max")]
        public long TempMax { get; set; }

        [JsonProperty("pressure")]
        public long Pressure { get; set; }

        [JsonProperty("humidity")]
        public long Humidity { get; set; }
    }

    public partial class Sys
    {
        [JsonProperty("type")]
        public long Type { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("sunrise")]
        public long Sunrise { get; set; }

        [JsonProperty("sunset")]
        public long Sunset { get; set; }
    }

    public partial class Weather
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("main")]
        public string Main { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("icon")]
        public string Icon { get; set; }
    }

    public partial class Wind
    {
        [JsonProperty("speed")]
        public double Speed { get; set; }

        [JsonProperty("deg")]
        public long Deg { get; set; }
    }

    public partial class OpenWheatherMapProxy
    {
        public static OpenWheatherMapProxy FromJson(string json) => JsonConvert.DeserializeObject<OpenWheatherMapProxy>(json, ET2_2_Tiempo.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this OpenWheatherMapProxy self) => JsonConvert.SerializeObject(self, ET2_2_Tiempo.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    public partial class OpenWheatherMapProxy
    {
        public async static Task<OpenWheatherMapProxy> RecuperaTiempo(double lat, double lon)
        {
            HttpClient http = new HttpClient();
            var respuesta = await http.GetAsync("https://api.openweathermap.org/data/2.5/weather?lat=" + 
                lat.ToString() + "&lon=" + lon.ToString() + "&units=metric&lang=es&appid=ce2115597119bec13b55ebb562d2d277");
            var resultado = await respuesta.Content.ReadAsStringAsync();
            OpenWheatherMapProxy data = OpenWheatherMapProxy.FromJson(resultado);
            return data;

        }
    }


}
